development:
  adapter: postgresql
  encoding: utf8
  database: testapp_development
  pool: 5
  username: developer
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: testapp_test
  pool: 5
  username: developer
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: testapp_production
  pool: 5
  username: developer
  password:

